# Generated by Django 4.0.3 on 2022-04-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recurso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
